### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tevinjeffrey.rutgerssoc/com.tevinjeffrey.rutgerssoc.ui.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.tevinjeffrey.rutgerssoc.model.Course$Sections.isOpenStatus()' on a null object reference

### ISSUE THREAD

**Issue by tevjef** [tevjef/Rutgers-Course-Tracker#10]
```bash
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tevinjeffrey.rutgerssoc/com.tevinjeffrey.rutgerssoc.ui.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.tevinjeffrey.rutgerssoc.model.Course$Sections.isOpenStatus()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2314)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388)
	at android.app.ActivityThread.access$800(ActivityThread.java:148)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5312)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.tevinjeffrey.rutgerssoc.model.Course$Sections.isOpenStatus()' on a null object reference
	at com.tevinjeffrey.rutgerssoc.adapters.SectionInfoAdapter.setToolBarColor(SectionInfoAdapter.java:320)
	at com.tevinjeffrey.rutgerssoc.adapters.SectionInfoAdapter.setData(SectionInfoAdapter.java:175)
	at com.tevinjeffrey.rutgerssoc.adapters.SectionInfoAdapter.init(SectionInfoAdapter.java:171)
	at com.tevinjeffrey.rutgerssoc.ui.SectionInfoFragment.inflateViews(SectionInfoFragment.java:74)
	at com.tevinjeffrey.rutgerssoc.ui.SectionInfoFragment.onCreateView(SectionInfoFragment.java:51)
	at android.app.Fragment.performCreateView(Fragment.java:2053)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1049)
	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1871)
	at android.app.Activity.performCreateCommon(Activity.java:5948)
	at android.app.Activity.performCreate(Activity.java:5955)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1128)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267)
	... 10 more

```

**Comment by tevjef** [comment]
duplicate of issue #3
