### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Throwable.getMessage()' on a null object reference

### ISSUE THREAD

**Issue by tevjef** [tevjef/Rutgers-Course-Tracker#67]
```bash
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Throwable.getMessage()' on a null object reference
	at com.tevinjeffrey.rutgersct.MyApplication$CrashReportingTree.e(SourceFile:116)
	at aez.e(SourceFile:191)
	at timber.log.Timber.e(SourceFile:59)
	at com.tevinjeffrey.rutgersct.ui.SubjectFragment$ListFutureCallback.onCompleted(SourceFile:275)
	at com.tevinjeffrey.rutgersct.ui.SubjectFragment$ListFutureCallback.onCompleted(SourceFile:250)
	at com.koushikdutta.async.future.SimpleFuture.a(SourceFile:107)
	at com.koushikdutta.async.future.SimpleFuture.setComplete(SourceFile:141)
	at com.koushikdutta.async.future.SimpleFuture.setComplete(SourceFile:128)
	at tv.run(SourceFile:244)
	at iy.run(SourceFile:57)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5312)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

```

**Comment by jorielcolon4-ux** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
	at net.kdt.pojavlaunch.JavaGUILauncherActivity.getJavaVersion(JavaGUILauncherActivity.java:406)
	at net.kdt.pojavlaunch.JavaGUILauncherActivity.access$200(JavaGUILauncherActivity.java:47)
	at net.kdt.pojavlaunch.JavaGUILauncherActivity$JarFileProperties.read(JavaGUILauncherActivity.java:237)
	at net.kdt.pojavlaunch.JavaGUILauncherActivity.runModInstaller(JavaGUILauncherActivity.java:246)
	at net.kdt.pojavlaunch.JavaGUILauncherActivity.lambda$startModInstaller$3$net-kdt-pojavlaunch-JavaGUILauncherActivity(JavaGUILauncherActivity.java:260)
	at net.kdt.pojavlaunch.JavaGUILauncherActivity$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1564)
