### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference

### ISSUE THREAD

**Issue by tevjef** [tevjef/Rutgers-Course-Tracker#8]
```bash
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
	at android.app.BackStackRecord.setBackNameOverrides(BackStackRecord.java:1633)
	at android.app.BackStackRecord.remapSharedElements(BackStackRecord.java:1088)
	at android.app.BackStackRecord.configureTransitions(BackStackRecord.java:1295)
	at android.app.BackStackRecord.beginTransition(BackStackRecord.java:1010)
	at android.app.BackStackRecord.popFromBackStack(BackStackRecord.java:1516)
	at android.app.FragmentManagerImpl.popBackStackState(FragmentManager.java:1506)
	at android.app.FragmentManagerImpl$2.run(FragmentManager.java:490)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1454)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5312)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

```

**Comment by airtel121** [comment]
Same issue any solution?

**Comment by tevjef** [comment]
I believe I get this by passing a null list to the `AdapterView`.

**Comment by airtel121** [comment]
I dont think so because its happen when we use Shared Element transition and then we press back key .
So that FragmentManager's popBackStack() will cause this issue.
When i remove shared element then error goes.

**Comment by sonique6784** [comment]
HI @airtel121 ,
Same issue here with the transition, did you fix it?

**Comment by pangduckwai** [comment]
I just got the same problem. I suspect everyone got this problem read the same stackoverflow entry (http://stackoverflow.com/questions/26561579/how-to-start-shared-element-transition-using-fragments), which mistakenly call the original fragment's setSharedElementReturnTransition(). I changed my code to call the method on the target fragment, and seems solved the problem.

**Comment by Anjanapuzhakkal** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
what to do
